# 生产环境配置
server:
  port: 8080
  # 生产环境关闭压缩以减少CPU使用
  compression:
    enabled: false

spring:
  # 数据库配置 - 生产环境
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:usdt_trading_platform}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:UsdtTrading123!}
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 200
      # 生产环境关闭监控页面
      stat-view-servlet:
        enabled: false
  
  # Redis配置 - 生产环境
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      lettuce:
        pool:
          max-active: 500
          max-idle: 50
          min-idle: 10

# 区块链配置 - 生产环境使用主网
blockchain:
  tron:
    use-testnet: false
    platform-wallet-address: ${PLATFORM_WALLET_ADDRESS}
    platform-wallet-private-key: ${PLATFORM_WALLET_PRIVATE_KEY:7cd80e83e0d35855affb7829dce76c53a18eec788530a7512b63008bd361bb84}
    fee-wallet-address: ${FEE_WALLET_ADDRESS}
    fee-wallet-private-key: ${FEE_WALLET_PRIVATE_KEY:7cd80e83e0d35855affb7829dce76c53a18eec788530a7512b63008bd361bb84}

# 日志配置 - 生产环境
logging:
  level:
    root: warn
    com.usdttrading: info
    org.springframework.security: warn
  file:
    name: /app/logs/usdt-trading.log
    max-size: 500MB
    max-history: 30

# 业务配置 - 生产环境严格限制
business:
  trading:
    min-trade-amount: 100
    max-trade-amount: 50000
    withdrawal-fee: 5
    auto-approval-limit: 1000
  security:
    max-login-attempts: 5
    account-lock-minutes: 30

# 监控配置 - 生产环境
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
  health:
    mail:
      enabled: false

# 关闭开发工具
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false