# USDT交易平台配置文件
server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
  tomcat:
    threads:
      max: 200
      min-spare: 50

spring:
  application:
    name: usdt-trading-platform
  
  # 环境配置
  profiles:
    active: dev
  
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usdt_trading_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    
    # Druid连接池配置
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: ${DRUID_PASSWORD:admin123}
        reset-enable: false
        allow: ""
        deny: ""
  
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 10s
      database: 0
      lettuce:
        pool:
          max-active: 200
          max-idle: 20
          min-idle: 5
          max-wait: -1ms
  
  # 邮件配置
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  
  # Jackson配置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.usdttrading.entity

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从head中读取token
  is-read-head: true
  # token前缀
  token-prefix: Bearer

# 区块链配置
blockchain:
  tron:
    # 是否使用测试网
    use-testnet: true
    # 主网节点
    mainnet-url: https://api.trongrid.io
    # 测试网节点  
    testnet-url: https://api.shasta.trongrid.io
    # USDT合约地址 (TRC20)
    usdt-contract-address: ${USDT_CONTRACT_ADDRESS:TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t}
    # 平台钱包配置
    platform-wallet-address: ${PLATFORM_WALLET_ADDRESS:}
    platform-wallet-private-key: ${PLATFORM_WALLET_PRIVATE_KEY:}
    # Gas费钱包配置
    fee-wallet-address: ${FEE_WALLET_ADDRESS:}
    fee-wallet-private-key: ${FEE_WALLET_PRIVATE_KEY:}
    # 交易确认数
    confirmation-count: 19
    # Gas配置
    gas-price: 420000000
    gas-limit: 1000000

# 业务配置
business:
  # 交易配置
  trading:
    # 最小交易金额
    min-trade-amount: 100
    # 最大交易金额
    max-trade-amount: 50000
    # 提款手续费
    withdrawal-fee: 5
    # 最小提款金额
    withdrawal-min-amount: 50
    # 每日提款限额
    withdrawal-daily-limit: 10000
    # 自动审核限额
    auto-approval-limit: 1000
    # KYC必要限额
    kyc-required-limit: 1000
  
  # 安全配置
  security:
    # RSA密钥对
    rsa:
      public-key: ${RSA_PUBLIC_KEY:}
      private-key: ${RSA_PRIVATE_KEY:}
    # 登录失败最大次数
    max-login-attempts: 5
    # 账户锁定时间(分钟)
    account-lock-minutes: 30
    # 验证码有效期(分钟)
    captcha-expire-minutes: 5
  
  # 文件存储配置
  file:
    # 上传目录
    upload-path: ${FILE_UPLOAD_PATH:/tmp/uploads}
    # 访问前缀
    access-prefix: /files
    # 允许的文件类型
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx

# 日志配置
logging:
  level:
    com.usdttrading: info
    org.springframework.security: debug
    org.springframework.web: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/usdt-trading.log
    max-size: 100MB
    max-history: 30

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true

# 开发工具配置
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: auth
      display-name: 认证模块
      paths-to-match: /auth/**
    - group: user
      display-name: 用户模块  
      paths-to-match: /user/**
    - group: admin
      display-name: 管理模块
      paths-to-match: /admin/**